# https://www.fastruby.io/blog/ruby/code-quality/how-we-use-rubocop-and-standardrb.html
require:
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - public/**/*
    - vendor/**/*
