#inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vagrant/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'lib/generators/**/*'
    - 'node_modules/**/*'
    - 'test/dummy/**/*'

Metrics:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '[]'
    '%i': '[]'
    '%q': '[]'
    '%Q': '[]'
    '%r': '[]'
    '%s': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '[]'

Performance/Casecmp:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EndAlignment:
  AutoCorrect: true
